module.exports = {
  projects: [
    '<rootDir>/apps/client',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api/core/feature',
    '<rootDir>/libs/api/intercept/feature',
    '<rootDir>/libs/api/endpoint/data-access',
    '<rootDir>/libs/shared/data-access',
    '<rootDir>/libs/api/project/data-access',
    '<rootDir>/libs/api/project/feature',
    '<rootDir>/libs/api/project/utils',
    '<rootDir>/libs/api/shared/data-access',
    '<rootDir>/libs/api/endpoint/feature',
    '<rootDir>/libs/api/response/feature',
    '<rootDir>/libs/api/response/data-access',
    '<rootDir>/libs/client/shared/ui',
    '<rootDir>/libs/client/shell/feature',
    '<rootDir>/libs/client/shell/ui',
    '<rootDir>/libs/client/projects/feature',
    '<rootDir>/libs/client/shell/ui/layout',
    '<rootDir>/libs/client/shell/ui/top-bar',
    '<rootDir>/libs/client/shell/ui/logo',
    '<rootDir>/libs/client/shell/ui/theme-switcher',
  ],
};
