version: "3.8"

services:
  api:
    container_name: aymme-be
    image: aymme/api:latest
    environment:
      - DATABASE_URL=mongodb://root:root@mongodb:27017/aymme?authSource=admin
    depends_on:
      - mongodb
    ports:
      - "3333:3333"

  client:
    container_name: aymme-fe
    image: aymme/client:latest
    environment:
      - API_URL=http://localhost:3333/api
    ports:
      - "7333:80"
    depends_on:
      - api

  mongodb:
    image: 'bitnami/mongodb:5.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongo-db:/bitnami/mongodb'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_DATABASE=aymme

volumes:
  mongo-db:
