version: '3.9'

services:
  mongodb:
    image: 'bitnami/mongodb:5.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongo-db:/bitnami/mongodb'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongo-db:
