name: Publish Client Docker Image

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest release version
        id: keydb
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse latest Tag version
        uses: actions/github-script@v6
        id: get-tag-id
        with:
          script: |
            const tagId = "${{ steps.keydb.outputs.tag_name }}";
            core.setOutput('tagId', tagId.substring(1));

      - name: Release version
        run: echo ${{ steps.get-tag-id.outputs.tagId }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: aymme/client
          tags: |
            type=raw,value=${{ steps.get-tag-id.outputs.tagId }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build Client Code
        working-directory: .
        run: |
          yarn install --frozen-lockfile
          yarn build client

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/client/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
