name: Release AYMME

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#      - name: setup node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16
#          cache: 'yarn'
#      - run: yarn install --frozen-lockfile
#      - run: yarn release --ci
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_api_to_docker:
    name: Deploy API to Docker
    uses: ./.github/workflows/release-api.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    needs: release

  deploy_client_to_docker:
    name: Deploy Client to Docker
    uses: ./.github/workflows/release-client.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    needs: release


